// Generated by gencpp from file gazebo_msgs/ApplyBodyWrench.msg
// DO NOT EDIT!


#ifndef GAZEBO_MSGS_MESSAGE_APPLYBODYWRENCH_H
#define GAZEBO_MSGS_MESSAGE_APPLYBODYWRENCH_H

#include <ros/service_traits.h>


#include <gazebo_msgs/ApplyBodyWrenchRequest.h>
#include <gazebo_msgs/ApplyBodyWrenchResponse.h>


namespace gazebo_msgs
{

struct ApplyBodyWrench
{

typedef ApplyBodyWrenchRequest Request;
typedef ApplyBodyWrenchResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ApplyBodyWrench
} // namespace gazebo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_msgs::ApplyBodyWrench > {
  static const char* value()
  {
    return "585b9f9618aa0581b207e2f2d90866bc";
  }

  static const char* value(const ::gazebo_msgs::ApplyBodyWrench&) { return value(); }
};

template<>
struct DataType< ::gazebo_msgs::ApplyBodyWrench > {
  static const char* value()
  {
    return "gazebo_msgs/ApplyBodyWrench";
  }

  static const char* value(const ::gazebo_msgs::ApplyBodyWrench&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_msgs::ApplyBodyWrenchRequest> should match 
// service_traits::MD5Sum< ::gazebo_msgs::ApplyBodyWrench > 
template<>
struct MD5Sum< ::gazebo_msgs::ApplyBodyWrenchRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs::ApplyBodyWrench >::value();
  }
  static const char* value(const ::gazebo_msgs::ApplyBodyWrenchRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs::ApplyBodyWrenchRequest> should match 
// service_traits::DataType< ::gazebo_msgs::ApplyBodyWrench > 
template<>
struct DataType< ::gazebo_msgs::ApplyBodyWrenchRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs::ApplyBodyWrench >::value();
  }
  static const char* value(const ::gazebo_msgs::ApplyBodyWrenchRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_msgs::ApplyBodyWrenchResponse> should match 
// service_traits::MD5Sum< ::gazebo_msgs::ApplyBodyWrench > 
template<>
struct MD5Sum< ::gazebo_msgs::ApplyBodyWrenchResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs::ApplyBodyWrench >::value();
  }
  static const char* value(const ::gazebo_msgs::ApplyBodyWrenchResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs::ApplyBodyWrenchResponse> should match 
// service_traits::DataType< ::gazebo_msgs::ApplyBodyWrench > 
template<>
struct DataType< ::gazebo_msgs::ApplyBodyWrenchResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs::ApplyBodyWrench >::value();
  }
  static const char* value(const ::gazebo_msgs::ApplyBodyWrenchResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_MSGS_MESSAGE_APPLYBODYWRENCH_H
