// Generated by gencpp from file gazebo_msgs/ApplyJointEffort.msg
// DO NOT EDIT!


#ifndef GAZEBO_MSGS_MESSAGE_APPLYJOINTEFFORT_H
#define GAZEBO_MSGS_MESSAGE_APPLYJOINTEFFORT_H

#include <ros/service_traits.h>


#include <gazebo_msgs/ApplyJointEffortRequest.h>
#include <gazebo_msgs/ApplyJointEffortResponse.h>


namespace gazebo_msgs
{

struct ApplyJointEffort
{

typedef ApplyJointEffortRequest Request;
typedef ApplyJointEffortResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ApplyJointEffort
} // namespace gazebo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_msgs::ApplyJointEffort > {
  static const char* value()
  {
    return "c0039811b8cc919490b3cff748cdf46b";
  }

  static const char* value(const ::gazebo_msgs::ApplyJointEffort&) { return value(); }
};

template<>
struct DataType< ::gazebo_msgs::ApplyJointEffort > {
  static const char* value()
  {
    return "gazebo_msgs/ApplyJointEffort";
  }

  static const char* value(const ::gazebo_msgs::ApplyJointEffort&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_msgs::ApplyJointEffortRequest> should match 
// service_traits::MD5Sum< ::gazebo_msgs::ApplyJointEffort > 
template<>
struct MD5Sum< ::gazebo_msgs::ApplyJointEffortRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs::ApplyJointEffort >::value();
  }
  static const char* value(const ::gazebo_msgs::ApplyJointEffortRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs::ApplyJointEffortRequest> should match 
// service_traits::DataType< ::gazebo_msgs::ApplyJointEffort > 
template<>
struct DataType< ::gazebo_msgs::ApplyJointEffortRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs::ApplyJointEffort >::value();
  }
  static const char* value(const ::gazebo_msgs::ApplyJointEffortRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_msgs::ApplyJointEffortResponse> should match 
// service_traits::MD5Sum< ::gazebo_msgs::ApplyJointEffort > 
template<>
struct MD5Sum< ::gazebo_msgs::ApplyJointEffortResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs::ApplyJointEffort >::value();
  }
  static const char* value(const ::gazebo_msgs::ApplyJointEffortResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs::ApplyJointEffortResponse> should match 
// service_traits::DataType< ::gazebo_msgs::ApplyJointEffort > 
template<>
struct DataType< ::gazebo_msgs::ApplyJointEffortResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs::ApplyJointEffort >::value();
  }
  static const char* value(const ::gazebo_msgs::ApplyJointEffortResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_MSGS_MESSAGE_APPLYJOINTEFFORT_H
