// Generated by gencpp from file gazebo_msgs/BodyRequest.msg
// DO NOT EDIT!


#ifndef GAZEBO_MSGS_MESSAGE_BODYREQUEST_H
#define GAZEBO_MSGS_MESSAGE_BODYREQUEST_H

#include <ros/service_traits.h>


#include <gazebo_msgs/BodyRequestRequest.h>
#include <gazebo_msgs/BodyRequestResponse.h>


namespace gazebo_msgs
{

struct BodyRequest
{

typedef BodyRequestRequest Request;
typedef BodyRequestResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct BodyRequest
} // namespace gazebo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_msgs::BodyRequest > {
  static const char* value()
  {
    return "5eade9afe7f232d78005bd0cafeab755";
  }

  static const char* value(const ::gazebo_msgs::BodyRequest&) { return value(); }
};

template<>
struct DataType< ::gazebo_msgs::BodyRequest > {
  static const char* value()
  {
    return "gazebo_msgs/BodyRequest";
  }

  static const char* value(const ::gazebo_msgs::BodyRequest&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_msgs::BodyRequestRequest> should match 
// service_traits::MD5Sum< ::gazebo_msgs::BodyRequest > 
template<>
struct MD5Sum< ::gazebo_msgs::BodyRequestRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs::BodyRequest >::value();
  }
  static const char* value(const ::gazebo_msgs::BodyRequestRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs::BodyRequestRequest> should match 
// service_traits::DataType< ::gazebo_msgs::BodyRequest > 
template<>
struct DataType< ::gazebo_msgs::BodyRequestRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs::BodyRequest >::value();
  }
  static const char* value(const ::gazebo_msgs::BodyRequestRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_msgs::BodyRequestResponse> should match 
// service_traits::MD5Sum< ::gazebo_msgs::BodyRequest > 
template<>
struct MD5Sum< ::gazebo_msgs::BodyRequestResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs::BodyRequest >::value();
  }
  static const char* value(const ::gazebo_msgs::BodyRequestResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs::BodyRequestResponse> should match 
// service_traits::DataType< ::gazebo_msgs::BodyRequest > 
template<>
struct DataType< ::gazebo_msgs::BodyRequestResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs::BodyRequest >::value();
  }
  static const char* value(const ::gazebo_msgs::BodyRequestResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_MSGS_MESSAGE_BODYREQUEST_H
