// Generated by gencpp from file gazebo_msgs/GetJointProperties.msg
// DO NOT EDIT!


#ifndef GAZEBO_MSGS_MESSAGE_GETJOINTPROPERTIES_H
#define GAZEBO_MSGS_MESSAGE_GETJOINTPROPERTIES_H

#include <ros/service_traits.h>


#include <gazebo_msgs/GetJointPropertiesRequest.h>
#include <gazebo_msgs/GetJointPropertiesResponse.h>


namespace gazebo_msgs
{

struct GetJointProperties
{

typedef GetJointPropertiesRequest Request;
typedef GetJointPropertiesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetJointProperties
} // namespace gazebo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_msgs::GetJointProperties > {
  static const char* value()
  {
    return "7b30be900f50aa21efec4a0ec92d91c9";
  }

  static const char* value(const ::gazebo_msgs::GetJointProperties&) { return value(); }
};

template<>
struct DataType< ::gazebo_msgs::GetJointProperties > {
  static const char* value()
  {
    return "gazebo_msgs/GetJointProperties";
  }

  static const char* value(const ::gazebo_msgs::GetJointProperties&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_msgs::GetJointPropertiesRequest> should match 
// service_traits::MD5Sum< ::gazebo_msgs::GetJointProperties > 
template<>
struct MD5Sum< ::gazebo_msgs::GetJointPropertiesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs::GetJointProperties >::value();
  }
  static const char* value(const ::gazebo_msgs::GetJointPropertiesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs::GetJointPropertiesRequest> should match 
// service_traits::DataType< ::gazebo_msgs::GetJointProperties > 
template<>
struct DataType< ::gazebo_msgs::GetJointPropertiesRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs::GetJointProperties >::value();
  }
  static const char* value(const ::gazebo_msgs::GetJointPropertiesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_msgs::GetJointPropertiesResponse> should match 
// service_traits::MD5Sum< ::gazebo_msgs::GetJointProperties > 
template<>
struct MD5Sum< ::gazebo_msgs::GetJointPropertiesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs::GetJointProperties >::value();
  }
  static const char* value(const ::gazebo_msgs::GetJointPropertiesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs::GetJointPropertiesResponse> should match 
// service_traits::DataType< ::gazebo_msgs::GetJointProperties > 
template<>
struct DataType< ::gazebo_msgs::GetJointPropertiesResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs::GetJointProperties >::value();
  }
  static const char* value(const ::gazebo_msgs::GetJointPropertiesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_MSGS_MESSAGE_GETJOINTPROPERTIES_H
