// Generated by gencpp from file gazebo_msgs/GetLinkState.msg
// DO NOT EDIT!


#ifndef GAZEBO_MSGS_MESSAGE_GETLINKSTATE_H
#define GAZEBO_MSGS_MESSAGE_GETLINKSTATE_H

#include <ros/service_traits.h>


#include <gazebo_msgs/GetLinkStateRequest.h>
#include <gazebo_msgs/GetLinkStateResponse.h>


namespace gazebo_msgs
{

struct GetLinkState
{

typedef GetLinkStateRequest Request;
typedef GetLinkStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetLinkState
} // namespace gazebo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_msgs::GetLinkState > {
  static const char* value()
  {
    return "09d6c98cce97b35f7ab9bd70300657ab";
  }

  static const char* value(const ::gazebo_msgs::GetLinkState&) { return value(); }
};

template<>
struct DataType< ::gazebo_msgs::GetLinkState > {
  static const char* value()
  {
    return "gazebo_msgs/GetLinkState";
  }

  static const char* value(const ::gazebo_msgs::GetLinkState&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_msgs::GetLinkStateRequest> should match 
// service_traits::MD5Sum< ::gazebo_msgs::GetLinkState > 
template<>
struct MD5Sum< ::gazebo_msgs::GetLinkStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs::GetLinkState >::value();
  }
  static const char* value(const ::gazebo_msgs::GetLinkStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs::GetLinkStateRequest> should match 
// service_traits::DataType< ::gazebo_msgs::GetLinkState > 
template<>
struct DataType< ::gazebo_msgs::GetLinkStateRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs::GetLinkState >::value();
  }
  static const char* value(const ::gazebo_msgs::GetLinkStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_msgs::GetLinkStateResponse> should match 
// service_traits::MD5Sum< ::gazebo_msgs::GetLinkState > 
template<>
struct MD5Sum< ::gazebo_msgs::GetLinkStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs::GetLinkState >::value();
  }
  static const char* value(const ::gazebo_msgs::GetLinkStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs::GetLinkStateResponse> should match 
// service_traits::DataType< ::gazebo_msgs::GetLinkState > 
template<>
struct DataType< ::gazebo_msgs::GetLinkStateResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs::GetLinkState >::value();
  }
  static const char* value(const ::gazebo_msgs::GetLinkStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_MSGS_MESSAGE_GETLINKSTATE_H
