// Generated by gencpp from file gazebo_msgs/GetLightProperties.msg
// DO NOT EDIT!


#ifndef GAZEBO_MSGS_MESSAGE_GETLIGHTPROPERTIES_H
#define GAZEBO_MSGS_MESSAGE_GETLIGHTPROPERTIES_H

#include <ros/service_traits.h>


#include <gazebo_msgs/GetLightPropertiesRequest.h>
#include <gazebo_msgs/GetLightPropertiesResponse.h>


namespace gazebo_msgs
{

struct GetLightProperties
{

typedef GetLightPropertiesRequest Request;
typedef GetLightPropertiesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetLightProperties
} // namespace gazebo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_msgs::GetLightProperties > {
  static const char* value()
  {
    return "df2cef87e13e2e6990e81e8aaa454c19";
  }

  static const char* value(const ::gazebo_msgs::GetLightProperties&) { return value(); }
};

template<>
struct DataType< ::gazebo_msgs::GetLightProperties > {
  static const char* value()
  {
    return "gazebo_msgs/GetLightProperties";
  }

  static const char* value(const ::gazebo_msgs::GetLightProperties&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_msgs::GetLightPropertiesRequest> should match 
// service_traits::MD5Sum< ::gazebo_msgs::GetLightProperties > 
template<>
struct MD5Sum< ::gazebo_msgs::GetLightPropertiesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs::GetLightProperties >::value();
  }
  static const char* value(const ::gazebo_msgs::GetLightPropertiesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs::GetLightPropertiesRequest> should match 
// service_traits::DataType< ::gazebo_msgs::GetLightProperties > 
template<>
struct DataType< ::gazebo_msgs::GetLightPropertiesRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs::GetLightProperties >::value();
  }
  static const char* value(const ::gazebo_msgs::GetLightPropertiesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_msgs::GetLightPropertiesResponse> should match 
// service_traits::MD5Sum< ::gazebo_msgs::GetLightProperties > 
template<>
struct MD5Sum< ::gazebo_msgs::GetLightPropertiesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs::GetLightProperties >::value();
  }
  static const char* value(const ::gazebo_msgs::GetLightPropertiesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs::GetLightPropertiesResponse> should match 
// service_traits::DataType< ::gazebo_msgs::GetLightProperties > 
template<>
struct DataType< ::gazebo_msgs::GetLightPropertiesResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs::GetLightProperties >::value();
  }
  static const char* value(const ::gazebo_msgs::GetLightPropertiesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_MSGS_MESSAGE_GETLIGHTPROPERTIES_H
