// Generated by gencpp from file gazebo_msgs/JointRequest.msg
// DO NOT EDIT!


#ifndef GAZEBO_MSGS_MESSAGE_JOINTREQUEST_H
#define GAZEBO_MSGS_MESSAGE_JOINTREQUEST_H

#include <ros/service_traits.h>


#include <gazebo_msgs/JointRequestRequest.h>
#include <gazebo_msgs/JointRequestResponse.h>


namespace gazebo_msgs
{

struct JointRequest
{

typedef JointRequestRequest Request;
typedef JointRequestResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct JointRequest
} // namespace gazebo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_msgs::JointRequest > {
  static const char* value()
  {
    return "0be1351618e1dc030eb7959d9a4902de";
  }

  static const char* value(const ::gazebo_msgs::JointRequest&) { return value(); }
};

template<>
struct DataType< ::gazebo_msgs::JointRequest > {
  static const char* value()
  {
    return "gazebo_msgs/JointRequest";
  }

  static const char* value(const ::gazebo_msgs::JointRequest&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_msgs::JointRequestRequest> should match 
// service_traits::MD5Sum< ::gazebo_msgs::JointRequest > 
template<>
struct MD5Sum< ::gazebo_msgs::JointRequestRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs::JointRequest >::value();
  }
  static const char* value(const ::gazebo_msgs::JointRequestRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs::JointRequestRequest> should match 
// service_traits::DataType< ::gazebo_msgs::JointRequest > 
template<>
struct DataType< ::gazebo_msgs::JointRequestRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs::JointRequest >::value();
  }
  static const char* value(const ::gazebo_msgs::JointRequestRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_msgs::JointRequestResponse> should match 
// service_traits::MD5Sum< ::gazebo_msgs::JointRequest > 
template<>
struct MD5Sum< ::gazebo_msgs::JointRequestResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs::JointRequest >::value();
  }
  static const char* value(const ::gazebo_msgs::JointRequestResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs::JointRequestResponse> should match 
// service_traits::DataType< ::gazebo_msgs::JointRequest > 
template<>
struct DataType< ::gazebo_msgs::JointRequestResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs::JointRequest >::value();
  }
  static const char* value(const ::gazebo_msgs::JointRequestResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_MSGS_MESSAGE_JOINTREQUEST_H
