// Generated by gencpp from file gazebo_msgs/SetJointProperties.msg
// DO NOT EDIT!


#ifndef GAZEBO_MSGS_MESSAGE_SETJOINTPROPERTIES_H
#define GAZEBO_MSGS_MESSAGE_SETJOINTPROPERTIES_H

#include <ros/service_traits.h>


#include <gazebo_msgs/SetJointPropertiesRequest.h>
#include <gazebo_msgs/SetJointPropertiesResponse.h>


namespace gazebo_msgs
{

struct SetJointProperties
{

typedef SetJointPropertiesRequest Request;
typedef SetJointPropertiesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetJointProperties
} // namespace gazebo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_msgs::SetJointProperties > {
  static const char* value()
  {
    return "15a76e921b1410c698d82782ea5fa370";
  }

  static const char* value(const ::gazebo_msgs::SetJointProperties&) { return value(); }
};

template<>
struct DataType< ::gazebo_msgs::SetJointProperties > {
  static const char* value()
  {
    return "gazebo_msgs/SetJointProperties";
  }

  static const char* value(const ::gazebo_msgs::SetJointProperties&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_msgs::SetJointPropertiesRequest> should match 
// service_traits::MD5Sum< ::gazebo_msgs::SetJointProperties > 
template<>
struct MD5Sum< ::gazebo_msgs::SetJointPropertiesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs::SetJointProperties >::value();
  }
  static const char* value(const ::gazebo_msgs::SetJointPropertiesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs::SetJointPropertiesRequest> should match 
// service_traits::DataType< ::gazebo_msgs::SetJointProperties > 
template<>
struct DataType< ::gazebo_msgs::SetJointPropertiesRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs::SetJointProperties >::value();
  }
  static const char* value(const ::gazebo_msgs::SetJointPropertiesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_msgs::SetJointPropertiesResponse> should match 
// service_traits::MD5Sum< ::gazebo_msgs::SetJointProperties > 
template<>
struct MD5Sum< ::gazebo_msgs::SetJointPropertiesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs::SetJointProperties >::value();
  }
  static const char* value(const ::gazebo_msgs::SetJointPropertiesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs::SetJointPropertiesResponse> should match 
// service_traits::DataType< ::gazebo_msgs::SetJointProperties > 
template<>
struct DataType< ::gazebo_msgs::SetJointPropertiesResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs::SetJointProperties >::value();
  }
  static const char* value(const ::gazebo_msgs::SetJointPropertiesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_MSGS_MESSAGE_SETJOINTPROPERTIES_H
