// Generated by gencpp from file gazebo_msgs/SetLightProperties.msg
// DO NOT EDIT!


#ifndef GAZEBO_MSGS_MESSAGE_SETLIGHTPROPERTIES_H
#define GAZEBO_MSGS_MESSAGE_SETLIGHTPROPERTIES_H

#include <ros/service_traits.h>


#include <gazebo_msgs/SetLightPropertiesRequest.h>
#include <gazebo_msgs/SetLightPropertiesResponse.h>


namespace gazebo_msgs
{

struct SetLightProperties
{

typedef SetLightPropertiesRequest Request;
typedef SetLightPropertiesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetLightProperties
} // namespace gazebo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_msgs::SetLightProperties > {
  static const char* value()
  {
    return "cd58c48ac21e5165abf13bcaa9c079b4";
  }

  static const char* value(const ::gazebo_msgs::SetLightProperties&) { return value(); }
};

template<>
struct DataType< ::gazebo_msgs::SetLightProperties > {
  static const char* value()
  {
    return "gazebo_msgs/SetLightProperties";
  }

  static const char* value(const ::gazebo_msgs::SetLightProperties&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_msgs::SetLightPropertiesRequest> should match 
// service_traits::MD5Sum< ::gazebo_msgs::SetLightProperties > 
template<>
struct MD5Sum< ::gazebo_msgs::SetLightPropertiesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs::SetLightProperties >::value();
  }
  static const char* value(const ::gazebo_msgs::SetLightPropertiesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs::SetLightPropertiesRequest> should match 
// service_traits::DataType< ::gazebo_msgs::SetLightProperties > 
template<>
struct DataType< ::gazebo_msgs::SetLightPropertiesRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs::SetLightProperties >::value();
  }
  static const char* value(const ::gazebo_msgs::SetLightPropertiesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_msgs::SetLightPropertiesResponse> should match 
// service_traits::MD5Sum< ::gazebo_msgs::SetLightProperties > 
template<>
struct MD5Sum< ::gazebo_msgs::SetLightPropertiesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs::SetLightProperties >::value();
  }
  static const char* value(const ::gazebo_msgs::SetLightPropertiesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs::SetLightPropertiesResponse> should match 
// service_traits::DataType< ::gazebo_msgs::SetLightProperties > 
template<>
struct DataType< ::gazebo_msgs::SetLightPropertiesResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs::SetLightProperties >::value();
  }
  static const char* value(const ::gazebo_msgs::SetLightPropertiesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_MSGS_MESSAGE_SETLIGHTPROPERTIES_H
