// Generated by gencpp from file gazebo_msgs/SetModelState.msg
// DO NOT EDIT!


#ifndef GAZEBO_MSGS_MESSAGE_SETMODELSTATE_H
#define GAZEBO_MSGS_MESSAGE_SETMODELSTATE_H

#include <ros/service_traits.h>


#include <gazebo_msgs/SetModelStateRequest.h>
#include <gazebo_msgs/SetModelStateResponse.h>


namespace gazebo_msgs
{

struct SetModelState
{

typedef SetModelStateRequest Request;
typedef SetModelStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetModelState
} // namespace gazebo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_msgs::SetModelState > {
  static const char* value()
  {
    return "5b3ab0281d4f5445def017e3a2e4a07b";
  }

  static const char* value(const ::gazebo_msgs::SetModelState&) { return value(); }
};

template<>
struct DataType< ::gazebo_msgs::SetModelState > {
  static const char* value()
  {
    return "gazebo_msgs/SetModelState";
  }

  static const char* value(const ::gazebo_msgs::SetModelState&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_msgs::SetModelStateRequest> should match 
// service_traits::MD5Sum< ::gazebo_msgs::SetModelState > 
template<>
struct MD5Sum< ::gazebo_msgs::SetModelStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs::SetModelState >::value();
  }
  static const char* value(const ::gazebo_msgs::SetModelStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs::SetModelStateRequest> should match 
// service_traits::DataType< ::gazebo_msgs::SetModelState > 
template<>
struct DataType< ::gazebo_msgs::SetModelStateRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs::SetModelState >::value();
  }
  static const char* value(const ::gazebo_msgs::SetModelStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_msgs::SetModelStateResponse> should match 
// service_traits::MD5Sum< ::gazebo_msgs::SetModelState > 
template<>
struct MD5Sum< ::gazebo_msgs::SetModelStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs::SetModelState >::value();
  }
  static const char* value(const ::gazebo_msgs::SetModelStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs::SetModelStateResponse> should match 
// service_traits::DataType< ::gazebo_msgs::SetModelState > 
template<>
struct DataType< ::gazebo_msgs::SetModelStateResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs::SetModelState >::value();
  }
  static const char* value(const ::gazebo_msgs::SetModelStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_MSGS_MESSAGE_SETMODELSTATE_H
