// Generated by gencpp from file gazebo_msgs/SetPhysicsProperties.msg
// DO NOT EDIT!


#ifndef GAZEBO_MSGS_MESSAGE_SETPHYSICSPROPERTIES_H
#define GAZEBO_MSGS_MESSAGE_SETPHYSICSPROPERTIES_H

#include <ros/service_traits.h>


#include <gazebo_msgs/SetPhysicsPropertiesRequest.h>
#include <gazebo_msgs/SetPhysicsPropertiesResponse.h>


namespace gazebo_msgs
{

struct SetPhysicsProperties
{

typedef SetPhysicsPropertiesRequest Request;
typedef SetPhysicsPropertiesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPhysicsProperties
} // namespace gazebo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_msgs::SetPhysicsProperties > {
  static const char* value()
  {
    return "97e2057080558ce4730434b5fae75c91";
  }

  static const char* value(const ::gazebo_msgs::SetPhysicsProperties&) { return value(); }
};

template<>
struct DataType< ::gazebo_msgs::SetPhysicsProperties > {
  static const char* value()
  {
    return "gazebo_msgs/SetPhysicsProperties";
  }

  static const char* value(const ::gazebo_msgs::SetPhysicsProperties&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_msgs::SetPhysicsPropertiesRequest> should match 
// service_traits::MD5Sum< ::gazebo_msgs::SetPhysicsProperties > 
template<>
struct MD5Sum< ::gazebo_msgs::SetPhysicsPropertiesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs::SetPhysicsProperties >::value();
  }
  static const char* value(const ::gazebo_msgs::SetPhysicsPropertiesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs::SetPhysicsPropertiesRequest> should match 
// service_traits::DataType< ::gazebo_msgs::SetPhysicsProperties > 
template<>
struct DataType< ::gazebo_msgs::SetPhysicsPropertiesRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs::SetPhysicsProperties >::value();
  }
  static const char* value(const ::gazebo_msgs::SetPhysicsPropertiesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_msgs::SetPhysicsPropertiesResponse> should match 
// service_traits::MD5Sum< ::gazebo_msgs::SetPhysicsProperties > 
template<>
struct MD5Sum< ::gazebo_msgs::SetPhysicsPropertiesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs::SetPhysicsProperties >::value();
  }
  static const char* value(const ::gazebo_msgs::SetPhysicsPropertiesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs::SetPhysicsPropertiesResponse> should match 
// service_traits::DataType< ::gazebo_msgs::SetPhysicsProperties > 
template<>
struct DataType< ::gazebo_msgs::SetPhysicsPropertiesResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs::SetPhysicsProperties >::value();
  }
  static const char* value(const ::gazebo_msgs::SetPhysicsPropertiesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_MSGS_MESSAGE_SETPHYSICSPROPERTIES_H
