// Generated by gencpp from file gazebo_msgs/SpawnModel.msg
// DO NOT EDIT!


#ifndef GAZEBO_MSGS_MESSAGE_SPAWNMODEL_H
#define GAZEBO_MSGS_MESSAGE_SPAWNMODEL_H

#include <ros/service_traits.h>


#include <gazebo_msgs/SpawnModelRequest.h>
#include <gazebo_msgs/SpawnModelResponse.h>


namespace gazebo_msgs
{

struct SpawnModel
{

typedef SpawnModelRequest Request;
typedef SpawnModelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SpawnModel
} // namespace gazebo_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_msgs::SpawnModel > {
  static const char* value()
  {
    return "9ed9c82c96abe1a00c3e8cdaeee24413";
  }

  static const char* value(const ::gazebo_msgs::SpawnModel&) { return value(); }
};

template<>
struct DataType< ::gazebo_msgs::SpawnModel > {
  static const char* value()
  {
    return "gazebo_msgs/SpawnModel";
  }

  static const char* value(const ::gazebo_msgs::SpawnModel&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_msgs::SpawnModelRequest> should match 
// service_traits::MD5Sum< ::gazebo_msgs::SpawnModel > 
template<>
struct MD5Sum< ::gazebo_msgs::SpawnModelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs::SpawnModel >::value();
  }
  static const char* value(const ::gazebo_msgs::SpawnModelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs::SpawnModelRequest> should match 
// service_traits::DataType< ::gazebo_msgs::SpawnModel > 
template<>
struct DataType< ::gazebo_msgs::SpawnModelRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs::SpawnModel >::value();
  }
  static const char* value(const ::gazebo_msgs::SpawnModelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_msgs::SpawnModelResponse> should match 
// service_traits::MD5Sum< ::gazebo_msgs::SpawnModel > 
template<>
struct MD5Sum< ::gazebo_msgs::SpawnModelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_msgs::SpawnModel >::value();
  }
  static const char* value(const ::gazebo_msgs::SpawnModelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_msgs::SpawnModelResponse> should match 
// service_traits::DataType< ::gazebo_msgs::SpawnModel > 
template<>
struct DataType< ::gazebo_msgs::SpawnModelResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_msgs::SpawnModel >::value();
  }
  static const char* value(const ::gazebo_msgs::SpawnModelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_MSGS_MESSAGE_SPAWNMODEL_H
